/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeaveType = IDL.Variant({
  'halfDayFirstHalf' : IDL.Null,
  'noLeave' : IDL.Null,
  'fullDayLeave' : IDL.Null,
  'halfDaySecondHalf' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'swipeIn' : IDL.Text,
  'date' : IDL.Text,
  'breakfastAtOffice' : IDL.Bool,
  'swipeOut' : IDL.Text,
  'leaveType' : LeaveType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QueryRange = IDL.Record({
  'endDate' : IDL.Text,
  'startDate' : IDL.Text,
});
export const SwipeResponse = IDL.Record({
  'isSwipeIn' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRecord' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecord' : IDL.Func([IDL.Text], [IDL.Opt(AttendanceRecord)], ['query']),
  'getRecordsByDateRange' : IDL.Func(
      [QueryRange],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRecord' : IDL.Func([AttendanceRecord], [], []),
  'swipeAction' : IDL.Func([IDL.Bool, IDL.Text], [SwipeResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeaveType = IDL.Variant({
    'halfDayFirstHalf' : IDL.Null,
    'noLeave' : IDL.Null,
    'fullDayLeave' : IDL.Null,
    'halfDaySecondHalf' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'swipeIn' : IDL.Text,
    'date' : IDL.Text,
    'breakfastAtOffice' : IDL.Bool,
    'swipeOut' : IDL.Text,
    'leaveType' : LeaveType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QueryRange = IDL.Record({
    'endDate' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const SwipeResponse = IDL.Record({
    'isSwipeIn' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRecord' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecord' : IDL.Func([IDL.Text], [IDL.Opt(AttendanceRecord)], ['query']),
    'getRecordsByDateRange' : IDL.Func(
        [QueryRange],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRecord' : IDL.Func([AttendanceRecord], [], []),
    'swipeAction' : IDL.Func([IDL.Bool, IDL.Text], [SwipeResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };